name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
      NEO4J_URI:       ${{ secrets.NEO4J_URI }}
      NEO4J_USERNAME:  ${{ secrets.NEO4J_USERNAME }}
      NEO4J_PASSWORD:  ${{ secrets.NEO4J_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
